AWS_ACCESS_KEY_ID: 'AKIAIS2WNXZVEFFSM4LQ'
AWS_SECRET_ACCESS_KEY: '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'
S3_BUCKET_NAME: 'wexchange'
PUSHER_APP_ID: '440752'
PUSHER_KEY: '90c45b2b119a4d2bb432'
PUSHER_SECRET: '58fe3b6d19d25e2af45e'
PUSHER_CLUSTER: 'us2'
